# Uncomment the next line to define a global platform for your project
# platform :ios, '14.3'

target 'Check' do
  use_frameworks!
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Database'
end
