# Uncomment the next line to define a global platform for your project
# platform :ios, '14.3'

target 'EntryPass' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EntryPass
pod 'KeychainSwift', '~> 19.0'
end
